### ISSUE TITLE
i have no idea

### ISSUE THREAD

**Issue by GladYard** [TrollTaylor/Fabric-Hider#18]
Internal Exception: Java.lang.NoSuchMethodError: 'netminecraft.class_2960 net.minecraft.class_2817.nethod_36169)'

**Comment by TrollTaylor** [comment]
Show full log

**Comment by GladYard** [comment]
[latest.log](https://github.com/TrollTaylor/Fabric-Hider/files/13500567/latest.log)

**Comment by GladYard** [comment]
hello?

**Comment by TrollTaylor** [comment]
This isn't because of this mod. It is whatever this is from "[20:38:22] [Render thread/INFO]: Connecting to mc.nexus.mn, 25565"
